load("@bazel_lib//:bzl_library.bzl", "bzl_library")

exports_files([
    "cli.tpl.sh",
    "dev-run.tpl.sh",
    "image-cli-launcher.sh",
])

bzl_library(
    name = "constants",
    srcs = ["constants.bzl"],
    visibility = [
        "//private:__subpackages__",
    ],
)

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
    visibility = [
        "//prisma:__pkg__",
        "//private/prisma:__subpackages__",
    ],
    deps = [
        "//private:npm_js_binary",
        "//private/docker:bzl",
        "@aspect_rules_js//js:defs",
        "@bazel_lib//lib:copy_to_bin",
        "@bazel_lib//lib:write_source_files",
        "@bazel_skylib//lib:paths",
        "@bazel_skylib//rules:select_file",
        "@bazel_skylib//rules:write_file",
        "@rules_oci//oci:defs",
        "@tar.bzl//tar:tar",
    ],
)
