load("@dh_buildlib//prisma:defs.bzl", "prisma_deploy_image", "prisma_dev", "prisma_generate", "prisma_migrations", "prisma_schema")
load("@dh_buildlib//prisma/generators:defs.bzl", "prisma_client_js", "typegraphql_prisma")

package_group(
    name = "prisma-users",
    packages = [
        "//api/...",
        "//proxy/blob-auth/...",
        "//rest-api/...",
    ],
)

prisma_schema(
    name = "schema",
    db_url_env = "DATABASE_URL",
    schema = "schema.prisma",
    validate_db_url = "postgres://localhost/",
    visibility = ["//prisma:__subpackages__"],
)

prisma_generate(
    name = "generate",
    generators = [
        ":client.generator",
        ":typegraphql-prisma.generator",
    ],
    schema = ":schema",
)

prisma_client_js(
    name = "client",
    generate = ":generate",
    visibility = [
        ":prisma-users",
        "//prisma:__subpackages__",
    ],
)

typegraphql_prisma(
    name = "typegraphql-prisma",
    generate = ":generate",
    prisma_client = ":client",
    visibility = [
        ":prisma-users",
        "//prisma:__subpackages__",
    ],
)

prisma_dev(
    name = "prisma",
    db_service = "//dc:db",
    db_url = "postgres://postgres:zuuboi4eemae5ee2UNga@${DB_SERVICE}/",
    schema = ":schema",
    seed_script = "//prisma/seed",
)

prisma_migrations(
    name = "migrations",
    srcs = glob(["migrations/**"]),
    schema = ":schema",
    validation_db_image = "@postgres_image_linux_amd64",
    visibility = [
        "//prisma:__subpackages__",
    ],
)

prisma_deploy_image(
    name = "db-migrate",
    migrations = ":migrations",
    visibility = ["//:docker-image-users"],
)
