volumes:
  blob-store:

services:
  proxy:
    bazel-image: //proxy
    volumes:
      # TODO(#515): For now we only use nginx to read the blob store.
      # This is not ideal. Please read the comment on BlobStore.ts why.
      - blob-store:/blob_store:ro

  proxy-blob-auth:
    bazel-image: //proxy/blob-auth
    environment:
      DATABASE_URL: postgres://api_login:uh0Fahth8nu1ong9phai@db/postgres

  frontend:
    bazel-image: //frontend

  api:
    bazel-image: //api
    environment:
      GQL_ENABLE_PLAYGROUND: true
      DATABASE_URL: postgres://api_login:uh0Fahth8nu1ong9phai@db/postgres
    volumes:
      - blob-store:/blob_store

  rest-api:
    bazel-image: //rest-api
    environment:
      DATABASE_URL: postgres://api_login:uh0Fahth8nu1ong9phai@db/postgres

  db:
    bazel-image: "@postgres_image_linux_amd64"
    ports:
      - 5432 # for prisma.
    environment:
      POSTGRES_PASSWORD: zuuboi4eemae5ee2UNga

  # This service is used to perform db migrations, typically in a production
  # setting.
  #
  # To run it on a host with output to terminal:
  #   docker compose up db-migrate
  #
  # To run it on a host in detached mode:
  #   docker compose --profile deploy up -d
  #
  # Equivalents under bazel:
  #   bazelisk run //dc -- up db-migrate
  #   bazelisk run //dc -- --profile deploy up -d
  #
  db-migrate:
    bazel-image: //prisma:db-migrate
    profiles: [deploy] # does not come up by default; need to specify deploy profile or service explicitly
    environment:
      DATABASE_URL: postgres://postgres:zuuboi4eemae5ee2UNga@db/postgres
