load("@dh_buildlib//prisma:defs.bzl", "prisma_generate", "prisma_schema")
load("@dh_buildlib//prisma/generators:defs.bzl", "prisma_client")

prisma_schema(
    name = "schema",
    db_url_env = "DATABASE_URL",
    schema = "schema.prisma",
    validate_db_url = "postgres://localhost/",
)

prisma_generate(
    name = "generate",
    generators = [":client.generator"],
    schema = ":schema",
)

prisma_client(
    name = "client",
    generate = ":generate",
    visibility = [
        "//:__subpackages__",
    ],
)
