load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")

write_source_files(
    name = "docs",
    files = {
        "bazelrc.md": "//bazelrc:docs_defs",
        "docker.md": "//docker:docs_defs",
        "docker_repositories.md": "//docker:docs_repositories",
        "format.md": "//format:docs_defs",
        "gql_ts.md": "//gql/ts:docs_defs",
        "prisma.md": "//prisma:docs_defs",
        "react_app.md": "//react_app:docs_defs",
        "renovate.md": "//renovate:docs_defs",
        "tar.md": "//tar:docs_defs",
        "ts.md": "//ts:docs_defs",
        "ts_docker.md": "//ts/docker:docs_defs",
        "ts_setup.md": "//ts/setup:docs_defs",
    },
)
