load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("//private:ts_library.bzl", "ts_library")

ts_library(
    name = "src",
    srcs = glob(["**/*.ts"]),
    visibility = [
        "//private/docker/test:__pkg__",
        "//private/prisma/src:__pkg__",
    ],
    deps = [
        "//:node_modules/@types/argparse",
        "//:node_modules/@types/dockerode",
        "//:node_modules/@types/js-yaml",
        "//:node_modules/@types/node",
        "//:node_modules/@types/parse-passwd",
        "//:node_modules/@types/tar-stream",
        "//:node_modules/argparse",
        "//:node_modules/dockerode",
        "//:node_modules/js-yaml",
        "//:node_modules/parse-passwd",
        "//:node_modules/tar-stream",
        "//:node_modules/zod",
        "//private/js-lib/src",
    ],
)

js_binary(
    name = "dc-processor",
    data = [":src"],
    entry_point = "dc-processor.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "dc-runner",
    data = [":src"],
    entry_point = "dc-runner.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "js-image-layer",
    data = [":src"],
    entry_point = "js-image-layer.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "load-stamp-data",
    data = [":src"],
    entry_point = "load-stamp-data.js",
    visibility = ["//private/docker:__subpackages__"],
)

js_binary(
    name = "empty-dir-layer",
    data = [":src"],
    entry_point = "empty-dir-layer.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "build-dockerfile",
    data = [":src"],
    entry_point = "build-dockerfile.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "load-image",
    data = [":src"],
    entry_point = "load-image.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "extract-from-image",
    data = [":src"],
    entry_point = "extract-from-image.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "oci-pusher",
    data = [":src"],
    entry_point = "oci-pusher.js",
    visibility = ["//visibility:public"],
)
