load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load("@tar.bzl//tar:tar.bzl", "tar")

exports_files([
    "vite.config.mjs",
])

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
    visibility = [
        "//react_app:__pkg__",
    ],
    deps = [
        "//private:npm_js_binary",
        "//private/docker:bzl",
        "@aspect_rules_js//js:defs",
        "@aspect_rules_js//js:libs",
        "@aspect_rules_js//js:providers",
        "@bazel_lib//lib:copy_file",
        "@bazel_skylib//rules:copy_file",
        "@rules_oci//oci:defs",
        "@tar.bzl//tar:tar",
    ],
)

tar(
    name = "vite-config-tar",
    srcs = ["vite.config.mjs"],
    mtree = [
        "app/vite.config.mjs uid=0 gid=0 mode=0655 time=0 type=file content=$(location vite.config.mjs)",
    ],
    visibility = [
        "//visibility:public",
    ],
)

tar(
    name = "nginx-config-tar",
    srcs = ["default.conf"],
    mtree = [
        "etc/nginx/conf.d/default.conf uid=0 gid=0 mode=0655 time=0 type=file content=$(location default.conf)",
    ],
    visibility = [
        "//visibility:public",
    ],
)
