load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//private/tar:tar.bzl", "tar_auto_mtree")

exports_files([
    "vite.config.mjs",
])

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
    visibility = [
        "//react_app:__pkg__",
    ],
    deps = [
        "//private/docker:bzl",
        "//private/tar:bzl",
        "//private/ts:bzl",
        "@aspect_bazel_lib//lib:copy_file",
        "@aspect_rules_js//js:defs",
        "@aspect_rules_js//js:libs",
        "@aspect_rules_js//js:providers",
        "@rules_oci//oci:defs",
    ],
)

tar_auto_mtree(
    name = "vite-config-tar",
    srcs = ["vite.config.mjs"],
    replace_prefix = "app/",
    strip_prefix = package_name(),
    visibility = [
        "//visibility:public",
    ],
)

tar_auto_mtree(
    name = "nginx-config-tar",
    srcs = ["default.conf"],
    replace_prefix = "etc/nginx/conf.d/",
    strip_prefix = package_name(),
    visibility = [
        "//visibility:public",
    ],
)
