server {
  # Fallback to index.html in case a file does not exist.
  # This is to support client side routers (like react-router-dom).
  #
  # The vite dev server (in spa mode) has the same behavior (via the sirv single option):
  # https://vitejs.dev/config/shared-options.html#apptype
  # https://github.com/lukeed/sirv/tree/master/packages/sirv#optssingle
  root /usr/share/nginx/html;
  try_files $uri /index.html;
}
