load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("//private:ts_library.bzl", "ts_library")

ts_library(
    name = "src",
    deps = [
        "//:node_modules/@types/argparse",
        "//:node_modules/@types/node",
        "//:node_modules/argparse",
        "//private/js-lib/src",
    ],
)

js_binary(
    name = "gen-my-version",
    data = [":src"],
    entry_point = "gen-my-version.js",
    visibility = ["//my-version:__pkg__"],
)
