load("@aspect_rules_js//js:defs.bzl", "js_library")
load("//docker:defs.bzl", "extract_from_image")
load("//private:ts_library.bzl", "ts_test")
load("//ts/docker:defs.bzl", "docker_image_for_ts_test", "node_binary_image")

# Do not transpile from ts: Otherwise we'd need another package for the ts_project.
js_library(
    name = "node_app",
    testonly = 1,
    srcs = ["node_app.js"],
)

node_binary_image(
    name = "node_test",
    testonly = 1,
    data = [":node_app"],
    entry_point = ":node_app.js",
    volumes = ["/test_volume"],
)

docker_image_for_ts_test(
    name = "load_node_test_image",
    image = ":node_test",
)

extract_from_image(
    name = "extract_smoke_test",
    testonly = 1,
    out = "profile-for-test.txt",
    image = "@node_image",
    path = "etc/profile",
)

ts_test(
    name = "test",
    srcs = glob(["**/*.ts"]),
    data = [
        "profile-for-test.txt",
    ],
    tags = [
        "requires-network",  # docker socket
    ],
    deps = [
        ":load_node_test_image",
        "//:node_modules/jest-extended",
        "//:node_modules/testcontainers",
        "//private/docker/src",
    ],
)
