load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@rules_oci//oci:defs.bzl", "oci_image")
load("//:defs.bzl", "docker_image_for_ts_test")
load("//private:ts_library.bzl", "ts_test")

tar(
    name = "test-image-tar",
    srcs = ["file-in-image.txt"],
)

oci_image(
    name = "test-image",
    architecture = "amd64",
    os = "linux",
    tars = ["test-image-tar"],
)

docker_image_for_ts_test(
    name = "load_test_image",
    image = ":test-image",
)

docker_image_for_ts_test(
    name = "load_node_image",
    image = "@node_image_linux_amd64",
)

ts_test(
    name = "test",
    tags = [
        "requires-network",  # docker socket
    ],
    deps = [
        ":load_node_image",
        ":load_test_image",
        "//:node_modules/jest-extended",
        "//private/docker/src",
    ],
)
