load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("//private:ts_library.bzl", "ts_library")

ts_library(
    name = "src",
    srcs = glob(["**/*.ts"]),
    visibility = ["//private/setup/renovate/test:__pkg__"],
    deps = [
        "//:node_modules/@types/argparse",
        "//:node_modules/@types/esprima",
        "//:node_modules/@types/estree",
        "//:node_modules/@types/node",
        "//:node_modules/argparse",
        "//:node_modules/esprima",
    ],
)

js_binary(
    name = "update-config",
    data = [":src"],
    entry_point = "update-config.js",
    visibility = ["//visibility:public"],
)
