load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "eslint.dh-defaults.cjs",
    "test-pnpm-lock.sh",
    "default.npmrc",
    "babel.config.cjs",
    ".swcrc",
])

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
    visibility = [
        "//private:__subpackages__",
        "//ts:__subpackages__",
    ],
    deps = [
        "@aspect_bazel_lib//lib:write_source_files",
        "@aspect_rules_js//js:defs",
        "@aspect_rules_swc//swc:defs",
        "@aspect_rules_ts//ts:defs",
        "@bazel_skylib//rules:common_settings",
        "@bazel_skylib//rules:copy_file",
        "@bazel_skylib//rules:select_file",
    ],
)

# Not a js_library so we can refer to it as individual file in
# the jest config.
copy_to_bin(
    name = "file_transform",
    srcs = ["FileTransform.cjs"],
    visibility = ["//visibility:public"],
)
