# use dns resolver of docker-compose to resolve other servers
# this allows this container to run without/before the react, api and web containers run
resolver 127.0.0.11;

server {
    # define upstream addresses as variables (which results in upstream hosts beeing resolved during proxying rathern than on startup)
    set $frontend frontend:80;
    set $api api:4000;
    set $rest_api "rest-api:8000";
    set $proxy_blob_auth "proxy-blob-auth:8000";

    location /gql/v1 {
        rewrite ^/gql/v1/(.*) /$1 break;
        proxy_pass http://$api;
    }

    location /api/v1 {
        proxy_pass http://$rest_api;
    }

    location / {
        proxy_pass http://$frontend;
        # allow upgrade to websockets (for hot reload, but in general OK).
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location ~ "^/blob/(?<blob_type>[^/]+)/(?<blob_uuid>[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12})$" {
        limit_except GET {
          deny all;
        }

        # Authentication request: Call to the proxy-blob-auth service to
        # check authorization and get content type headers.

        auth_request /blob_auth;

        auth_request_set $in_content_type $upstream_http_content_type;
        auth_request_set $in_content_disposition $upstream_http_content_disposition;

        # Ignore the content type inferred by the nginx static serving module.
        types {}
        default_type "";

        # Set the content type headers from the proxy-blob-auth service store.
        add_header Content-Type $in_content_type;
        add_header Content-Disposition $in_content_disposition;

        # Rewrite to physical blob store path. Note that we *ignore* the
        # blob_type here: It is only relevant for metadata retrieval
        # (and we assume that UUIDv4s never collide).
        rewrite ^/blob/[^/]+/(..)(.*)$ /$1/$2 break;

        root /blob_store;

        # Performance, see
        # https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#enabling-sendfile
        sendfile on; # default, but be explicit.
        sendfile_max_chunk 1m; # educated guess, might need tweaking.
        tcp_nopush on;
    }

    location = /blob_auth {
        internal;
        # The variables $blob_type / $blob_uuid come from the regex above in the location match.
        proxy_pass              http://$proxy_blob_auth/$blob_type/$blob_uuid;
        proxy_pass_request_body off;
        proxy_set_header        Content-Length "";
    }
}
