load("@dh_buildlib//:defs.bzl", "node_binary_image")
load("@dh_buildlib//setup/defs:buildlib_setup.bzl", "buildlib_setup")

buildlib_setup(
    name = "buildlib_setup",
    enable_ts = True,
)

platform(
    name = "node_alpine_platform",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
        "@dh_buildlib//prisma/linux:musl",
        "@dh_buildlib//prisma/openssl:3",
    ],
)

node_binary_image(
    name = "musl_image",
    base = "@node_alpine_image_linux_amd64",
    data = ["//src"],
    entry_point = "//src:index.js",
    platform = ":node_alpine_platform",
)
