bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "aspect_rules_js", version = "2.2.0")
bazel_dep(name = "aspect_rules_ts", version = "3.5.0")
bazel_dep(name = "rules_oci", version = "2.2.2")
bazel_dep(name = "dh_buildlib", version = "0.0.0")
local_path_override(
    module_name = "dh_buildlib",
    path = "../../buildlib",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
use_repo(npm, "npm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(ts_version_from = "@npm//:typescript/resolved.json")
use_repo(rules_ts_ext, "npm_typescript")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "node_alpine_image",
    digest = "sha256:dc4d20572e425f9d4c68a6f9c382fbcfec3fa2f8ef0b12cb1d96feabdb479a48",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.9.0-alpine",
)
use_repo(oci, "node_alpine_image", "node_alpine_image_linux_amd64")
