bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "aspect_rules_js", version = "2.4.0")
bazel_dep(name = "aspect_rules_ts", version = "3.6.3")
bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "dh_buildlib", version = "0.0.0")
local_path_override(
    module_name = "dh_buildlib",
    path = "../../buildlib",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
use_repo(npm, "npm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(ts_version_from = "@npm//:typescript/resolved.json")
use_repo(rules_ts_ext, "npm_typescript")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "node_alpine_image",
    digest = "sha256:a34e14ef1df25b58258956049ab5a71ea7f0d498e41d0b514f4b8de09af09456",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.11.1-alpine",
)
use_repo(oci, "node_alpine_image", "node_alpine_image_linux_amd64")
