local_repository(
    name = "dh_buildlib",
    path = "../../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2(enable_prisma = True)

load("@dh_buildlib//repositories:docker_containers.bzl", "container_pull")

container_pull(
    name = "node_alpine_image",
    architecture = "amd64",
    digest = "sha256:415f3219943ef82fa45988acdaa7df05a0b52cabd3502095c59d34cbe28c1bc1",
    os = "linux",
    registry = "index.docker.io",
    repository = "node",
    tag = "22.3.0-alpine",  # ignored, doc only
)
