local_repository(
    name = "dh_buildlib",
    path = "../../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2(enable_prisma = True)

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "node_alpine_image",
    digest = "sha256:0a29d8a047149079bf48dab598f287815e39867d547e8f3935cfdece0a4379cc",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.8.0-alpine",  # ignored, doc only
)
