local_repository(
    name = "dh_buildlib",
    path = "../../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2()

load("@dh_buildlib//repositories:docker_containers.bzl", "container_pull")

container_pull(
    name = "node_image",
    architecture = "amd64",
    digest = "sha256:1155995dda741e93afe4b1c6ced2d01734a6ec69865cc0997daf1f4db7259a36",
    os = "linux",
    registry = "index.docker.io",
    repository = "node",
    tag = "20.7.0",  # ignored, doc only
)
