local_repository(
    name = "dh_buildlib",
    path = "../../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2()

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "node_image",
    digest = "sha256:ac6abe7d72fe2a535b331d862bf01e064abfd65c7b085c3ca6a51869014474a0",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.3.0",  # ignored, doc only
)
