load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@dh_buildlib_private_npm//:pnpm/package_json.bzl", _pnpm = "bin")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

exports_files([
    "test-pnpm-lock.sh",
    "default.npmrc",
])

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
    visibility = [
        "//private/setup:__pkg__",
    ],
    deps = [
        "//private/setup:write_setup_source_file",
        "@aspect_rules_js//js:defs",
        "@rules_shell//shell:rules_bzl",
    ],
)

_pnpm.pnpm_binary(
    name = "pnpm_raw",
    visibility = ["//visibility:public"],
)

# Tiny wrapper around pnpm: injects `--dir="$BUILD_WORKSPACE_DIRECTORY"`
sh_binary(
    name = "pnpm",
    srcs = [":pnpm.sh"],
    data = [":pnpm_raw"],
    env = {
        "PNPM_BIN": "$(rootpath :pnpm_raw)",
    },
    visibility = ["//visibility:public"],
)
