load("@dh_buildlib_private_npm//:defs.bzl", "npm_link_all_packages")
load("@local_config_platform//:constraints.bzl", "HOST_CONSTRAINTS")
load("@prisma_host_constraints//:constraints.bzl", "PRISMA_HOST_CONSTRAINTS")
load("//private/setup:buildlib_setup_no_npm.bzl", "buildlib_setup_no_npm")

npm_link_all_packages(name = "node_modules")

buildlib_setup_no_npm(
    name = "buildlib_setup",
    enable_java = True,
    enable_ts = True,
)

platform(
    name = "host_platform",
    # Auto-detected host platform constraints.
    constraint_values = HOST_CONSTRAINTS + PRISMA_HOST_CONSTRAINTS,
)
