module(
    name = "dh_buildlib",
    bazel_compatibility = [
        ">=8.0.0",  # for symbolic macros
    ],
)

# Non-Dev Dependencies

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "bazel_lib", version = "3.1.1")
bazel_dep(name = "rules_nodejs", version = "6.7.3")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "aspect_rules_js", version = "2.9.2")
bazel_dep(name = "aspect_rules_ts", version = "3.8.3")
bazel_dep(name = "rules_python", version = "1.8.0")
bazel_dep(name = "aspect_rules_swc", version = "2.6.0")
bazel_dep(name = "rules_oci", version = "2.2.7")
bazel_dep(name = "jq.bzl", version = "0.4.0")
bazel_dep(name = "tar.bzl", version = "0.7.0")
bazel_dep(name = "yq.bzl", version = "0.3.4")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.1")

# Internal non-dev repositories / extensions.

prisma_host_constraints = use_repo_rule("//private/prisma:repositories.bzl", "prisma_host_constraints")

prisma_host_constraints(name = "prisma_host_constraints")

ibazel_info = use_repo_rule("//private/docker:ibazel_info.bzl", "ibazel_info")

ibazel_info(name = "dh_buildlib_private_ibazel_info")

# Configure Node.js version: always take it from the root/main repository.

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version_from_nvmrc = "@@//:.nvmrc")

# npm / node_modules for buildlib itself.

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "dh_buildlib_private_npm",
    lifecycle_hooks_no_sandbox = False,
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "dh_buildlib_private_npm")

# npm / node_modules for the using repository.
# A basic npm setup is always required because we need at least prettier.
# It does not make sense to make notably .md formatting optional.
#
# In case we are building buildlib itself, this duplicates the
# `dh_buildlib_private_npm` repository as `npm` (which is not a problem).

npm.npm_translate_lock(
    name = "npm",
    lifecycle_hooks_no_sandbox = False,
    npmrc = "@@//:.npmrc",
    pnpm_lock = "@@//:pnpm-lock.yaml",
    verify_node_modules_ignored = "@@//:.bazelignore",
)

# use the repo for setup/defs/buildlib_setup.bzl
use_repo(npm, "npm")

# when buildlib is the root module, inject a fake npm repository.
# see the comment on setup/defs/buildlib_setup.bzl for more.
fake_npm_repository = use_repo_rule("//private/setup:fake_npm_repository.bzl", "fake_npm_repository")

fake_npm_repository(name = "fake_npm_repository")

override_repo(
    npm,
    npm = "fake_npm_repository",
)

# typescript for buildlib itself.

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    name = "dh_buildlib_private_typescript",
    ts_version_from = "@dh_buildlib_private_npm//:typescript/resolved.json",
)
use_repo(rules_ts_ext, "dh_buildlib_private_typescript")

# yq toolchain for the prisma engines repository.

yq_toolchain = use_extension("@yq.bzl//yq:extensions.bzl", "yq")
use_repo(
    yq_toolchain,
    "yq_darwin_amd64",
    "yq_darwin_arm64",
    "yq_linux_amd64",
    "yq_linux_arm64",
    "yq_linux_ppc64le",
    "yq_linux_s390x",
    "yq_windows_amd64",
)

prisma_engines_version = use_repo_rule("//private/prisma:engines_version.bzl", "engines_version")

prisma_engines_version(
    name = "prisma_engines_version",
    pnpm_lock = "@@//:pnpm-lock.yaml",  # always from root module
)

# prisma extension
#
# The extension is private, relevant bits are exposed via aliases
# (`//prisma:cli`) or rule attribute default values.
#
# - It pins prisma engines using the bazel lockfile.
# - It generates a different repository (which always fails) in case there is no
#   dependency on prisma.
#
# This is why we need an extension and not simply a use_repository.
prisma = use_extension("@dh_buildlib//private/prisma:prisma_extension.bzl", "prisma")
use_repo(prisma, "prisma")

# Dev dependencies

bazel_dep(name = "stardoc", version = "0.8.0", dev_dependency = True)
bazel_dep(name = "rules_jvm_external", version = "6.9", dev_dependency = True)

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven", dev_dependency = True)

# TODO(#1374, #1375): Re-align with tests/java if changed.
maven.install(
    artifacts = [
        "com.google.googlejavaformat:google-java-format:1.27.0",
    ],
    fail_if_repin_required = True,
    lock_file = "//:maven_install.json",
    resolver = "maven",
)
use_repo(maven, "maven")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci", dev_dependency = True)
oci.pull(
    name = "node_image",
    digest = "sha256:b2b2184ba9b78c022e1d6a7924ec6fba577adf28f15c9d9c457730cc4ad3807a",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "24.13.0",  # ignored, doc only
)
oci.pull(
    name = "postgres_image",
    digest = "sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2",
    image = "index.docker.io/library/postgres",
    platforms = ["linux/amd64"],
    tag = "18.1",  # ignored, doc only
)

# there are issues with prisma 5.x and alpine 3.21 regarding location of libssl, hence 3.20 was used here
# https://github.com/nodejs/docker-node/issues/2175
oci.pull(
    name = "node_alpine3.20_image",
    digest = "sha256:8fe019e0d57dbdce5f5c27c0b63d2775cf34b00e3755a7dea969802d7e0c2b25",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "24.1.0-alpine3.20",
)
use_repo(oci, "node_alpine3.20_image", "node_alpine3.20_image_linux_amd64", "node_image", "node_image_linux_amd64", "postgres_image", "postgres_image_linux_amd64")

# Pull in rules_python to set ignore_root_user_error = True.
# Workaround for https://git.datahouse.ch/datahouse/it-drone-bazel/issues/49
python = use_extension("@rules_python//python/extensions:python.bzl", "python", dev_dependency = True)
python.toolchain(
    ignore_root_user_error = True,
    python_version = "3.11",
)

compose = use_extension("@dh_buildlib//private/docker/compose:compose_extension.bzl", "compose_bin_extension")
compose.download(version = "5.0.1")
use_repo(compose, "dc_darwin_aarch64", "dc_darwin_x86_64", "dc_linux_aarch64", "dc_linux_x86_64", "dc_windows_aarch64", "dc_windows_x86_64")

register_toolchains(
    "@dh_buildlib//private/docker/compose:darwin_aarch64_toolchain",
    "@dh_buildlib//private/docker/compose:darwin_x86_64_toolchain",
    "@dh_buildlib//private/docker/compose:linux_aarch64_toolchain",
    "@dh_buildlib//private/docker/compose:linux_x86_64_toolchain",
    "@dh_buildlib//private/docker/compose:windows_x86_64_toolchain",
    "@dh_buildlib//private/docker/compose:windows_aarch64_toolchain",
)
