load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## Stardoc setup

# We put this first, since it seems that other transitive dependencies are too old.
# Moving to bazel modules (#5) would fix this.

http_archive(
    name = "io_bazel_stardoc",
    sha256 = "62bd2e60216b7a6fec3ac79341aa201e0956477e7c8f6ccc286f279ad1d96432",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/0.6.2/stardoc-0.6.2.tar.gz",
        "https://github.com/bazelbuild/stardoc/releases/download/0.6.2/stardoc-0.6.2.tar.gz",
    ],
)

load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")

stardoc_repositories()

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@io_bazel_stardoc//:deps.bzl", "stardoc_external_deps")

stardoc_external_deps()

load("@stardoc_maven//:defs.bzl", stardoc_pinned_maven_install = "pinned_maven_install")

stardoc_pinned_maven_install()

## Buildlib setup

load("//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2()

## Unittest setup

load("@bazel_skylib//lib:unittest.bzl", "register_unittest_toolchains")

register_unittest_toolchains()
