workspace(name = "dh_buildlib")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## Stardoc setup

# We put this first, since it seems that other transitive dependencies are too old.
# Moving to bazel modules (#5) would fix this.

http_archive(
    name = "io_bazel_stardoc",
    sha256 = "dd7f32f4fe2537ce2452c51f816a5962d48888a5b07de2c195f3b3da86c545d3",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/0.7.0/stardoc-0.7.0.tar.gz",
        "https://github.com/bazelbuild/stardoc/releases/download/0.7.0/stardoc-0.7.0.tar.gz",
    ],
)

load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")

stardoc_repositories()

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@io_bazel_stardoc//:deps.bzl", "stardoc_external_deps")

stardoc_external_deps()

load("@stardoc_maven//:defs.bzl", stardoc_pinned_maven_install = "pinned_maven_install")

stardoc_pinned_maven_install()

## Buildlib setup

load("//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("//repositories:setup2.bzl", "dh_buildlib_setup2")

dh_buildlib_setup2()

## Unittest setup

load("@bazel_skylib//lib:unittest.bzl", "register_unittest_toolchains")

register_unittest_toolchains()

load("//repositories:docker_containers.bzl", "container_pull")

container_pull(
    name = "node_image",
    architecture = "amd64",
    digest = "sha256:a3816e038e05ea70d2640c845c285f49e416bdae2481a7ff94fde96647a10607",
    os = "linux",
    registry = "index.docker.io",
    repository = "node",
    tag = "22.3.0",  # ignored, doc only
)
