load("@dh_buildlib//:defs.bzl", "bazelrc", "dh_docker_images_push", "format", "ts_setup")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

# Package group for visibility of docker images.
# Remove if you do not build docker images.
package_group(
    name = "docker-image-users",
    packages = [
        "//",  # for pushing
        "//dc",  # for docker-compose
    ],
)

bazelrc(
    name = "bazelrc",
)

ts_setup(
    name = "ts_setup",
)

format(name = "format")

dh_docker_images_push(
    name = "docker-push",
    images = {
        # Put your own images here (or leave empty to start with).
        "api": "//api",
        "frontend": "//frontend",
        "proxy": "//proxy",
        "proxy-blob-auth": "//proxy/blob-auth",
        "rest-api": "//rest-api",
    },
    repository_prefix = "it-bazel/example",
)
