load("@dh_buildlib//:defs.bzl", "dh_docker_images_push")
load("@dh_buildlib//setup/defs:buildlib_setup.bzl", "buildlib_setup")

# Package group for visibility of docker images.
# Remove if you do not build docker images.
package_group(
    name = "docker-image-users",
    packages = [
        "//",  # for pushing
        "//dc",  # for docker-compose
    ],
)

buildlib_setup(
    name = "buildlib_setup",
    enable_ts = True,
)

dh_docker_images_push(
    name = "docker-push",
    images = {
        # Put your own images here (or leave empty to start with).
        "api": "//api",
        "frontend": "//frontend",
        "proxy": "//proxy",
        "proxy-blob-auth": "//proxy/blob-auth",
        "rest-api": "//rest-api",
    },
    repository_prefix = "it-bazel/example",
)
