bazel_dep(name = "aspect_bazel_lib", version = "2.20.0")
bazel_dep(name = "aspect_rules_js", version = "2.4.0")
bazel_dep(name = "aspect_rules_ts", version = "3.6.3")
bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "dh_buildlib", version = "0.0.0")

# When setting up in a different repository this should be
# `git_override` (use it-bazel-new-repo to set it up).
local_path_override(
    module_name = "dh_buildlib",
    path = "../buildlib",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
use_repo(npm, "npm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(ts_version_from = "@npm//:typescript/resolved.json")
use_repo(rules_ts_ext, "npm_typescript")

# Docker images your project needs.
# - `node_image` is required by the base setup.
# - Remove others if you do not need them.

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "nginx_image",
    digest = "sha256:f5c017fb33c6db484545793ffb67db51cdd7daebee472104612f73a85063f889",
    image = "index.docker.io/library/nginx",
    platforms = ["linux/amd64"],
    tag = "1.29.0",  # ignored, doc only
)
oci.pull(
    name = "node_image",
    digest = "sha256:9a25b5a6f9a90218b73a62205f111e71de5e4289aee952b4dd7e86f7498f2544",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.11.1",  # ignored, doc only
)
oci.pull(
    name = "postgres_image",
    digest = "sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1",
    image = "index.docker.io/library/postgres",
    platforms = ["linux/amd64"],
    tag = "17.5",  # ignored, doc only
)
use_repo(oci, "nginx_image", "nginx_image_linux_amd64", "node_image", "node_image_linux_amd64", "postgres_image", "postgres_image_linux_amd64")
