# Pull in the dh_buildlib.
#
# When setting up in a different repository, replace this with
#
# load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
#
# git_repository(
#     name = "dh_buildlib",
#     commit = "<latest commit hash>",
#     remote = "git@git.datahouse.ch:datahouse/it-bazel.git",
#     strip_prefix = "buildlib",
# )
local_repository(
    name = "dh_buildlib",
    path = "../buildlib",
)

# Hack to make the renovate.json5 config from the repo root accessible
# in this subproject. See the renovate_config rule in the BUILD of the root
# package.
#
# When setting up in a different repository, remove this rule.
local_repository(
    name = "repo_root",
    path = "..",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

# If you do not need prisma, set `enable_prisma = False` or remove the argument entirely.
dh_buildlib_setup2(enable_prisma = True)

load("@dh_buildlib//repositories:docker_containers.bzl", "container_pull")

# Docker images your project needs.
# - `node_image` is required by the base setup.
# - Remove others if you do not need them.

container_pull(
    name = "nginx_image",
    architecture = "amd64",
    digest = "sha256:161ef4b1bf7effb350a2a9625cb2b59f69d54ec6059a8a155a1438d0439c593c",
    os = "linux",
    registry = "index.docker.io",
    repository = "nginx",
    tag = "1.25.3",  # ignored, doc only
)

container_pull(
    name = "node_image",
    architecture = "amd64",
    digest = "sha256:1f164f0b09e4ed367705243a41c00d8e3ead518de29c7d14e61d8f8d5e146e0e",
    os = "linux",
    registry = "index.docker.io",
    repository = "node",
    tag = "21.5.0",  # ignored, doc only
)

container_pull(
    name = "postgres_image",
    architecture = "amd64",
    digest = "sha256:60c91e0203ae5ccca0a251953742752cd16a129db181bc15559cca71420b188c",
    os = "linux",
    registry = "index.docker.io",
    repository = "postgres",
    tag = "16.1",  # ignored, doc only
)
