# Pull in the dh_buildlib.
#
# When setting up in a different repository, replace this with
#
# load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
#
# git_repository(
#     name = "dh_buildlib",
#     commit = "<latest commit hash>",
#     remote = "git@git.datahouse.ch:datahouse/it-bazel.git",
#     strip_prefix = "buildlib",
# )
local_repository(
    name = "dh_buildlib",
    path = "../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

# If you do not need prisma, set `enable_prisma = False` or remove the argument entirely.
dh_buildlib_setup2(enable_prisma = True)

load("@dh_buildlib//repositories:docker_containers.bzl", "container_pull")

# Docker images your project needs.
# - `node_image` is required by the base setup.
# - Remove others if you do not need them.

container_pull(
    name = "nginx_image",
    architecture = "amd64",
    digest = "sha256:1540e37eebb9abc5afa4256de1bade6542d50bf69b61b1dd855cb7804aaaf444",
    os = "linux",
    registry = "index.docker.io",
    repository = "nginx",
    tag = "1.27.1",  # ignored, doc only
)

container_pull(
    name = "node_image",
    architecture = "amd64",
    digest = "sha256:a3816e038e05ea70d2640c845c285f49e416bdae2481a7ff94fde96647a10607",
    os = "linux",
    registry = "index.docker.io",
    repository = "node",
    tag = "22.3.0",  # ignored, doc only
)

container_pull(
    name = "postgres_image",
    architecture = "amd64",
    digest = "sha256:c62fdb7fd6f519ef425c54760894c74e8d0cb04fbf4f7d3d79aafd86bae24edd",
    os = "linux",
    registry = "index.docker.io",
    repository = "postgres",
    tag = "16.4",  # ignored, doc only
)
