# Pull in the dh_buildlib.
#
# When setting up in a different repository, replace this with
#
# load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
#
# git_repository(
#     name = "dh_buildlib",
#     commit = "<latest commit hash>",
#     remote = "git@git.datahouse.ch:datahouse/it-bazel.git",
#     strip_prefix = "buildlib",
# )
local_repository(
    name = "dh_buildlib",
    path = "../buildlib",
)

load("@dh_buildlib//repositories:setup0.bzl", "dh_buildlib_setup0")

dh_buildlib_setup0()

load("@dh_buildlib//repositories:setup1.bzl", "dh_buildlib_setup1")

dh_buildlib_setup1()

load("@dh_buildlib//repositories:setup2.bzl", "dh_buildlib_setup2")

# If you do not need prisma, set `enable_prisma = False` or remove the argument entirely.
dh_buildlib_setup2(enable_prisma = True)

load("@rules_oci//oci:pull.bzl", "oci_pull")

# Docker images your project needs.
# - `node_image` is required by the base setup.
# - Remove others if you do not need them.

oci_pull(
    name = "nginx_image",
    digest = "sha256:bc2f6a7c8ddbccf55bdb19659ce3b0a92ca6559e86d42677a5a02ef6bda2fcef",
    image = "index.docker.io/library/nginx",
    platforms = ["linux/amd64"],
    tag = "1.27.3",  # ignored, doc only
)

oci_pull(
    name = "node_image",
    digest = "sha256:ac6abe7d72fe2a535b331d862bf01e064abfd65c7b085c3ca6a51869014474a0",
    image = "index.docker.io/library/node",
    platforms = ["linux/amd64"],
    tag = "23.3.0",  # ignored, doc only
)

oci_pull(
    name = "postgres_image",
    digest = "sha256:3267c505060a0052e5aa6e5175a7b41ab6b04da2f8c4540fc6e98a37210aa2d3",
    image = "index.docker.io/library/postgres",
    platforms = ["linux/amd64"],
    tag = "17.2",  # ignored, doc only
)
