load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@dh_buildlib//:defs.bzl", "ts_library")

ts_library(
    name = "src",
    deps = [
        "//prisma:prisma-client",
    ],
)

js_binary(
    name = "seed",
    data = ["src"],
    entry_point = "index.js",
    visibility = [
        "//prisma:__pkg__",
    ],
)
