"""The core, required setup macro."""

# Note: The load of @npm is faked with fake_npm_repository when buildlib is the
# root module (so notably when we are building stardocs).
#
# The npm repository generated by rules_js does not export the necessary bzl_library
# targets to add them as deps to the bzl_library containing buildlib_setup.
#
# As a result, stardoc generation would fail. To work around this, we create a
# fake npm repository that contains a noop `npm_link_all_packages` macro.
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//private/setup:buildlib_setup_no_npm.bzl", "buildlib_setup_no_npm")

def buildlib_setup(
        name,
        enable_ts = False):
    """Set-up a dh_buildlib workspace.

    - Provides `//:format` / `//:format.test`.
    - Validates various configurations for consistency.
    - Adds targets required by other dh_buildlib rules
      (e.g. `package_json` for `ts_library`).

    Use of this macro is required. dh_buildlib will not work without it.

    Note: Adding additional config consistency checks to this rule is explicitly
    **not** considered a breaking change (because they surface latent bugs in
    the usage configuration).

    Example: [`@examples//:buildlib_setup`](../../examples/BUILD.bazel#:~:text=name%20%3D%20%22buildlib_setup%22%2C)

    Args:
      name: Dummy name argument for tooling. Must be `buildlib_setup`.
      enable_ts: Whether to enable TypeScript support
    """

    npm_link_all_packages(name = "node_modules")

    buildlib_setup_no_npm(
        name = name,
        enable_ts = enable_ts,
    )
