bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "aspect_rules_js", version = "2.2.0")
bazel_dep(name = "aspect_rules_ts", version = "3.5.0")
bazel_dep(name = "rules_oci", version = "2.2.2")
bazel_dep(name = "dh_buildlib", version = "0.0.0")
local_path_override(
    module_name = "dh_buildlib",
    path = "../../buildlib",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
use_repo(npm, "npm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(ts_version_from = "@npm//:typescript/resolved.json")
use_repo(rules_ts_ext, "npm_typescript")
