load("@dh_buildlib//ts:defs.bzl", "ts_test")

ts_test(
    name = "test",
    srcs = glob(["**/*.ts"]),
    deps = [
        "//:node_modules/@types/node",
        "//:node_modules/graphql-upload",
        "//:node_modules/jest-extended",
        "//:node_modules/jest-mock-extended",
        "//api/src",
        "//prisma/rls",
    ],
)
